[env]
platform = espressif32
framework = arduino
board = esp32-s3-devkitc-1
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.partitions = max_app_8MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCONFIG_BT_NIMBLE_EXT_ADV=1

[env:car]
build_src_filter = -<*> +<car_main.cpp>
lib_deps =
    espressif/esp32-camera
    h2zero/NimBLE-Arduino@^2.1.0

[env:remote]
build_src_filter = -<*> +<remote_main.cpp>
lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    h2zero/NimBLE-Arduino@^2.1.0
